<div style="display:grid;grid-template-columns:1fr 1fr;gap:10px;">
<div class="field"><div class="label">Employee</div><select class="select" name="employee_id">@foreach($employees as $e)<option value="{{ $e->id }}" @selected((int)old('employee_id',$benefit->employee_id)===(int)$e->id)>{{ $e->last_name }}, {{ $e->first_name }}</option>@endforeach</select></div>
<div class="field"><div class="label">Benefit type</div><select class="select" name="benefit_type"><option value="sss" @selected(old('benefit_type',$benefit->benefit_type??'sss')==='sss')>sss</option><option value="pagibig" @selected(old('benefit_type',$benefit->benefit_type)==='pagibig')>pagibig</option><option value="philhealth" @selected(old('benefit_type',$benefit->benefit_type)==='philhealth')>philhealth</option><option value="other" @selected(old('benefit_type',$benefit->benefit_type)==='other')>other</option></select></div>
<div class="field"><div class="label">Membership number</div><input class="input" name="membership_number" value="{{ old('membership_number',$benefit->membership_number) }}"></div>
<div class="field"><div class="label">Status</div><select class="select" name="status"><option value="pending" @selected(old('status',$benefit->status??'pending')==='pending')>pending</option><option value="active" @selected(old('status',$benefit->status)==='active')>active</option><option value="inactive" @selected(old('status',$benefit->status)==='inactive')>inactive</option></select></div>
<div class="field"><div class="label">Start date</div><input class="input" type="date" name="start_date" value="{{ old('start_date',$benefit->start_date) }}"></div>
<div class="field"><div class="label">Eligibility date</div><input class="input" type="date" name="eligibility_date" value="{{ old('eligibility_date',$benefit->eligibility_date) }}"></div>
<div class="field" style="grid-column:1/-1;"><div class="label">Notes</div><textarea class="textarea" name="notes">{{ old('notes',$benefit->notes) }}</textarea></div>
</div>
